// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Scrapper is an autogenerated mock type for the Scrapper type
type Scrapper struct {
	mock.Mock
}

// GetPhishUrl provides a mock function with given fields: source
func (_m *Scrapper) GetPhishUrl(source string) ([]string, error) {
	ret := _m.Called(source)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewScrapper interface {
	mock.TestingT
	Cleanup(func())
}

// NewScrapper creates a new instance of Scrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScrapper(t mockConstructorTestingTNewScrapper) *Scrapper {
	mock := &Scrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
