// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	urls "fish-hunter/businesses/urls"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// FetchUrl provides a mock function with given fields: source
func (_m *UseCase) FetchUrl(source string) ([]urls.Domain, error) {
	ret := _m.Called(source)

	var r0 []urls.Domain
	if rf, ok := ret.Get(0).(func(string) []urls.Domain); ok {
		r0 = rf(source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]urls.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *UseCase) GetAll() ([]urls.Domain, error) {
	ret := _m.Called()

	var r0 []urls.Domain
	if rf, ok := ret.Get(0).(func() []urls.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]urls.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *UseCase) GetByID(id string) (urls.Domain, error) {
	ret := _m.Called(id)

	var r0 urls.Domain
	if rf, ok := ret.Get(0).(func(string) urls.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(urls.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
