name: Deploy on push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Copy files to docker container
      run: docker cp . fhg:/app
    - name: Kill the process
      continue-on-error: true
      run: docker exec fhg pkill dist
    - name: Download packages
      run: docker exec fhg go mod download
    - name: Build the project
      run: docker exec fhg go build -o dist
    - name: Run the project
      run: docker exec fhg ./dist > /dev/null 2>&1 &