name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Copy files to docker container
      run: docker cp . fhg:/app
    - name: Execute the updater
      run: docker exec fhg /bin/sh updater.sh