name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stopping old docker container
      run: docker stop /hunter || true
    - name: Removing old docker container
      run: docker rm /hunter || true
    - name: Build docker images
      run: docker build -t fish-hunter:1.0.0 .
    - name: Run docker
      run: docker run -itd -v /home/slave/fish-hunter/.env:/app/.env -v /home/slave/fish-hunter/key.pem:/app/key.pem -v /home/slave/fish-hunter/cert.pem:/app/cert.pem -p 443:443 --name hunter fish-hunter:1.0.0
